spring.datasource.url=jdbc:mysql://<plesk-host>:3306/admin_workshop
spring.datasource.username=adminWorkshop
spring.datasource.password=Anne4321!!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
