spring.datasource.url=jdbc:mysql://localhost:3306/workshops?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=workshops_user
spring.datasource.password=example

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

server.port=8080

spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=200MB


wailSalutem.security.jwt.secret=ThisIsASuperSecureJWTSecretKeyWithMoreThan32Chars!
wailSalutem.security.jwt.expiration-in-ms=3600000
